/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author golub
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        logintype = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        btreset = new javax.swing.JButton();
        tfusername = new javax.swing.JTextField();
        tfpassword = new javax.swing.JTextField();
        btlogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        forsubmit = new javax.swing.JButton();
        formob = new javax.swing.JTextField();
        foremail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hostel Management System");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Forte", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 200, 74));
        jLabel4.setText("Student / Admin Login");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 380, -1));

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(112, 255, 224));
        jLabel3.setText("Enter your username and password to login ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Forza", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 193, 193));
        jLabel6.setText("Username: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, 30));

        jLabel8.setFont(new java.awt.Font("Forza", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(251, 193, 193));
        jLabel8.setText("User Type");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        logintype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Administrator", "Student"}));
        logintype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logintypeActionPerformed(evt);
            }
        });
        jPanel1.add(logintype, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 190, -1));

        jLabel13.setFont(new java.awt.Font("Forza", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(251, 193, 193));
        jLabel13.setText("Password: ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        btreset.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btreset.setText("Reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });
        jPanel1.add(btreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 110, 30));

        tfusername.setBorder(null);
        tfusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });
        jPanel1.add(tfusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 200, 30));

        tfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(tfpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 200, 30));

        btlogin.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btlogin.setText("Login");
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        jPanel1.add(btlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 110, 30));

        jLabel2.setFont(new java.awt.Font("Underground NF", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hostel ManagemenT System ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\golub\\OneDrive\\Desktop\\HMS\\pexels-george-pak-7969103.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jTabbedPane5.addTab("Login", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(207, 177, 140));
        jLabel7.setText("Forgot Username/Password");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter Your Mobile No.");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\golub\\OneDrive\\Desktop\\HMS\\logo.png")); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Enter Your Email");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        forsubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forsubmit.setText("Submit");
        forsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forsubmitActionPerformed(evt);
            }
        });
        jPanel3.add(forsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        formob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formobActionPerformed(evt);
            }
        });
        jPanel3.add(formob, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 190, 30));

        foremail.setBorder(null);
        foremail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foremailActionPerformed(evt);
            }
        });
        jPanel3.add(foremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 190, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\golub\\OneDrive\\Desktop\\HMS\\001428 - Maastricht Blue Color Image - Schemecolor.png")); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 450, 430));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\golub\\OneDrive\\Desktop\\HMS\\neww.png")); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane5.addTab("Forgot Username / Passoword", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpasswordActionPerformed

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusernameActionPerformed

    private void foremailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foremailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foremailActionPerformed

    private void formobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formobActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
        tfusername.setText("");
        tfpassword.setText("");
    }//GEN-LAST:event_btresetActionPerformed

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
        // TODO add your handling code here:
                try{
            //open connection
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/idpassword", "root" , "root");
            //idpassowrd == database name
            //root = username
            //root = password
            String ID = tfusername.getText();
            String password = tfpassword.getText();
            String loginn = String.valueOf(logintype.getSelectedItem());
            
            Statement stm = con.createStatement();
            //mysql query to run
            String sql = "select * from loginrec where ID='"+ID+"' and password='"+password+"' and logintype='"+loginn+"'";
            ResultSet rs = stm.executeQuery(sql);
            
            if(rs.next()) {
                //if username and password is true then open next page
                JOptionPane.showMessageDialog(this, "Login Successful");
                if(logintype.getSelectedIndex()==0) {
                dispose(); //close login page
                 AdminPanel ap = new AdminPanel();
                 ap.show();
                }
                if(logintype.getSelectedIndex()==1) {
                dispose(); //close login page
                 StudentPanel sp = new StudentPanel();
                 sp.show();
                }
            }
            else {
                //if username and password are incorrect
                JOptionPane.showMessageDialog(this, "Username or Password wrong..");
                tfusername.setText("");
                tfpassword.setText("");
            }
            con.close();
            
        }catch(Exception e) {
            System.out.println(e.getMessage());
        }
        

        
    }//GEN-LAST:event_btloginActionPerformed

    private void logintypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logintypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logintypeActionPerformed

    private void forsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forsubmitActionPerformed
        // TODO add your handling code here:
        try{
            //open connection
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Student", "root" , "root");
            //idpassowrd == database name
            //root = username
            //root = password
            String email = foremail.getText();
            String mobile = formob.getText();
           
            Statement stm = con.createStatement();
            //mysql query to run
            String sql = "select * from student_details where email='"+email+"' and mobile='"+mobile+"'";
            ResultSet rs = stm.executeQuery(sql);
            
            if(rs.next()) {
                JOptionPane.showMessageDialog(this, "Your username is " + rs.getString("username") + "\n" + "Your password is " + rs.getString("password") );
            }
            else {
                //if username and password are incorrect
                JOptionPane.showMessageDialog(this, "Email and password not found..");
                foremail.setText("");
                formob.setText("");
            }
            con.close();        
        }catch(Exception e) {
            System.out.println(e.getMessage());
        }    
        
        
        
        
        
    }//GEN-LAST:event_forsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlogin;
    private javax.swing.JButton btreset;
    private javax.swing.JTextField foremail;
    private javax.swing.JTextField formob;
    private javax.swing.JButton forsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JComboBox<String> logintype;
    private javax.swing.JTextField tfpassword;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
